#!/usr/bin/env python3
"""Turns a recorded outbox trace into a TLA+ module for TraceOutbox.tla.

    trace2tla.py <trace.jsonl> <out dir>

Reads the lines the outbox observer of `crates/outbox/tests/pg.rs` writes,
one JSON object per event, and writes `<out dir>/<Name>.tla` defining
`TraceDef`, the sequence of steps the model takes, plus `<Name>.cfg`. Prints
`<Name>`. The mapping onto the model:

    published                 -> publish  (msg, uri, xid, pos)
    fetched, some messages    -> fetch    (d, of, horizon, limit, msgs)
    fetched, none             -> nofetch  (d, of, horizon, limit, msgs = <<>>)
    handled ok                -> handle   (d, msg)
    handled failed            -> nothing: the subscriber declined
    acked + dispatched batch  -> ack      (d, xid, pos): position and COMMIT, one step
    dispatched nothing        -> nothing: the nofetch already said it
    dispatched rolled_back    -> crash    (d), if a batch was fetched

Messages are named m1, m2, ... in order of publication; a dispatcher is
<<group, worker>>, the group without the `:worker` suffix several workers add.
"""
import json
import pathlib
import re
import sys


def tla_string(text):
    return '"' + text.replace('"', '\\"') + '"'


def record(**fields):
    def value(v):
        if isinstance(v, bool):
            return "TRUE" if v else "FALSE"
        if isinstance(v, int):
            return str(v)
        if isinstance(v, str):
            return tla_string(v)
        if isinstance(v, tuple):
            return "<<" + ", ".join(value(x) for x in v) + ">>"
        if isinstance(v, list):
            return "<<" + ", ".join(value(x) for x in v) + ">>"
        raise TypeError(v)

    return "[" + ", ".join(f"{k} |-> {value(v)}" for k, v in fields.items()) + "]"


def dispatcher(event):
    group, worker, of = event["group"], event["worker"], event["of"]
    if of > 1 and group.endswith(f":{worker}"):
        group = group[: -len(f":{worker}")]
    return (group, worker), of


def steps(lines):
    names = {}
    pending = {}  # dispatcher -> the batch was fetched and not yet closed
    acked = {}    # dispatcher -> the position acknowledged, awaiting COMMIT

    def name(message_id):
        if message_id not in names:
            raise SystemExit(f"a message was fetched that was never published: {message_id}")
        return names[message_id]

    for line in lines:
        e = json.loads(line)
        kind = e["event"]
        if kind == "published":
            names.setdefault(e["message_id"], f"m{len(names) + 1}")
            yield record(event="publish", msg=names[e["message_id"]], uri=e["uri"], xid=e["xid"], pos=e["position"])
            continue
        d, of = dispatcher(e)
        if kind == "fetched":
            msgs = [name(m) for m in e["messages"]]
            pending[d] = bool(msgs)
            yield record(event="fetch" if msgs else "nofetch", d=d, of=of,
                         horizon=e["horizon"], limit=e["limit"], msgs=msgs)
        elif kind == "handled":
            if e["ok"]:
                yield record(event="handle", d=d, msg=name(e["message_id"]))
        elif kind == "acked":
            acked[d] = (e["xid"], e["position"])
        elif kind == "dispatched":
            outcome = e["outcome"]
            if outcome == "batch":
                xid, pos = acked.pop(d)
                yield record(event="ack", d=d, xid=xid, pos=pos)
            elif outcome == "rolled_back":
                acked.pop(d, None)
                if pending.get(d):
                    yield record(event="crash", d=d)
            pending[d] = False
        else:
            raise SystemExit(f"unknown event: {kind}")


def main(trace, out):
    trace, out = pathlib.Path(trace), pathlib.Path(out)
    name = "Trace_" + re.sub(r"[^A-Za-z0-9_]", "_", trace.stem)
    body = ",\n  ".join(steps(trace.read_text().splitlines()))
    (out / f"{name}.tla").write_text(
        f"---- MODULE {name} ----\n"
        f"\\* Generated by trace2tla.py from {trace.name}; do not edit.\n"
        "EXTENDS TraceOutbox\n\n"
        f"TraceDef == <<\n  {body}\n>>\n\n"
        "====\n"
    )
    (out / f"{name}.cfg").write_text(
        "SPECIFICATION Spec\n"
        "CONSTANT Trace <- TraceDef\n"
        "INVARIANTS\n  TypeOK\n  DeliveredCommitted\n  NoPassedOver\n  OrderPerUri\n  NotFinished\n"
    )
    print(name)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    main(sys.argv[1], sys.argv[2])
